/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.tla.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 05-19-2015
 * 
 * XDoclet definition:
 * @struts.action
 */
public class GoMainUiAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		if (request.getSession().getAttribute("role").equals("secretary")) {
			//go to secretary main page
			// load data
			// redirection
			return mapping.findForward("goSecretaryMainUi");

		} else if (request.getSession().getAttribute("role").equals("teacher")) {
			// go to teacher main page
			// load data
			// redirection
			return mapping.findForward("goTeacherMainUi");

		} else if (request.getSession().getAttribute("role").equals("ta")) {
			// go to TA main page
			// load data
			// redirection
			return mapping.findForward("goTaMainUi");

		} else {
			request.setAttribute("msg", "ERROR: Permission denied.");
			return mapping.findForward("goLogin");
		}
	}
}