/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.tla.struts.action;

import javax.servlet.http.Cookie;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.tla.domain.Secretary;
import com.tla.domain.Teacher;
import com.tla.domain.Teachingassistant;
import com.tla.domain.Users;
import com.tla.service.imp.UsersServiceImp;
import com.tla.service.inter.UsersServiceInter;
import com.tla.struts.form.UserForm;
import com.tla.util.SecurityUtil;

/** 
 * MyEclipse Struts
 * Creation date: 05-19-2015
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="userForm" scope="request"
 */
public class LoginAction extends Action {
	private int expires = 7 * 24 * 60 * 60;// cookie save one week
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserForm userForm = (UserForm) form;
		Users user = new Users();
		user.setUsername(userForm.getUsername());
		user.setPassword(userForm.getPassword());
		user.setType(userForm.getType());

		String remember = userForm.getRemember();
		String username = userForm.getUsername();
		String password = userForm.getPassword();
		String type = userForm.getType();

		if (userForm.getType() != null) {
			UsersServiceInter usersServiceInter = new UsersServiceImp();
			Object obj = new Object();
			obj = usersServiceInter.checkUser(user);
			if (obj != null) {
				// set up cookie
				if ("remember".equals(remember)) {
					// The declaration of cookie
					Cookie autoCookie = null;
					// Get all of cookie
					Cookie cookies[] = request.getCookies();
					// traversal cookie to find whether autoCooie is existent
					for (Cookie cookie : cookies) {
						// Found out cookie
						if ("tla_autologin".equals(cookie.getName())) {
							autoCookie = cookie;
							// reset expires
							long time = System.currentTimeMillis() + expires
									* 1000;
							// MD5 encode cookie
							String newValue = type
									+ ":"
									+ username
									+ ":"
									+ time
									+ ":"
									+ SecurityUtil.MD5(type + ":" + username
											+ ":" + password + ":" + time);
							cookie.setValue(newValue);
						} else {
							// Not find out cookie. Create a cookie
							long time = System.currentTimeMillis() + expires
									* 1000;
							String cookieValue = type
									+ ":"
									+ username
									+ ":"
									+ time
									+ ":"
									+ SecurityUtil.MD5(type + ":" + username
											+ ":" + password + ":" + time);
							autoCookie = new Cookie("tla_autologin",
									cookieValue);
						}
					}
					autoCookie.setMaxAge(expires);
					response.addCookie(autoCookie);
				}
				request.getSession().setAttribute("userinfo", user);
				request.getSession().setAttribute("role", type);
				if (user.getType().equals("secretary")) {
					request.getSession().setAttribute("secretaryinfo",(Secretary) obj);
				} else if (user.getType().equals("teacher")) {
					request.getSession().setAttribute("teacherinfo",(Teacher) obj);
				} else if (user.getType().equals("ta")) {
					request.getSession().setAttribute("TAinfo",(Teachingassistant) obj);
				}
				return mapping.findForward("loginok");
			} else {
				request.setAttribute("msg","Incorrect username or password! Please try again.");
				return mapping.findForward("goLoginUi");
			}
		} else {
			request.setAttribute(
					"msg",
					"Sorry, this session has been expired. Please re-login to continue enjoying the service.");
			return mapping.findForward("goLoginUi");
		}
	}
}