/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.tla.struts.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-25-2015
 * 
 * XDoclet definition:
 * @struts.form name="assignTaForm"
 */
/**
 * @author lenovo
 * 
 */
public class AssignTaForm extends ActionForm {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String courseId;
	private String assginTa;

	public String getCourseId() {
		return courseId;
	}

	public void setCourseId(String courseId) {
		this.courseId = courseId;
	}

	public String getAssginTa() {
		return assginTa;
	}

	public void setAssginTa(String assginTa) {
		this.assginTa = assginTa;
	}

}