/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.tla.struts.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-20-2015
 * 
 * XDoclet definition:
 * @struts.form name="changePwdForm"
 */
public class ChangePwdForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** newPwd property */
	private String newPwd;

	/** oldPwd property */
	private String oldPwd;

	/*
	 * Generated Methods
	 */

	/** 
	 * Returns the newPwd.
	 * @return String
	 */
	public String getNewPwd() {
		return newPwd;
	}

	/** 
	 * Set the newPwd.
	 * @param newPwd The newPwd to set
	 */
	public void setNewPwd(String newPwd) {
		this.newPwd = newPwd;
	}

	/** 
	 * Returns the oldPwd.
	 * @return String
	 */
	public String getOldPwd() {
		return oldPwd;
	}

	/** 
	 * Set the oldPwd.
	 * @param oldPwd The oldPwd to set
	 */
	public void setOldPwd(String oldPwd) {
		this.oldPwd = oldPwd;
	}
}